# spring:
#   security:
#     oauth2:
#       client:
#         provider:
#           azure:
#             issuer-uri: https://login.microsoftonline.com/{-}/v2.0
#             user-name-attribute: EPICSBOT
#             authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#             token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#             user-info-uri: https://graph.microsoft.com/oidc/userinfo
#             jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#         registration:
#           azure:
#             provider: azure
#             client-id: {-}
#             client-secret: {-}
#             authorization-grant-type: authorization_code
#             redirect-uri: http://localhost:1010/auth-microsoft-custom/success
#             scope:
#               - openid
#               - email
#               - profile
